language: node_js
services:
  - docker
addons:
  sonarcloud:
    organization: 'gotreasa'
    token:
      secure: 'vDvMvRbsw/5qCmpnp7arURX3x1D6Ds8SrHWrN42PKGZDIoyE8hargI5toma5i0iqr69DXEngXcUBIGG5j7/945cFwky0fjJhnhlCTGiUIxqHsZSElFbrxJGpo57L4SiZRDUg4j03dXSbtrN4L3hroUOnUCarr49nyQUqUPET0RlTtPCPeEgx4dP+mUueSOSiMlFifgjP5phaPhNfYv2y4Z7QGf1lgl47TN8x2mupgQ+R+V9BRkGm3apjXOWPVKRDmGuJslfqpezzJAwtC+fXTOfynhh0WL5wPQKCLPyjHGXHZgUL2W6qpCS9avxnNbEzhs/xD4pEFUwqL1NKh68dfG9J+OnUFKkBIro+E9Vw4Pu+uSi7zWy1sCKhe4wbvLYd5QOJEkVG5oJouj+/zuwNkVhJKVN9/Po/pMLAU5ld6iYaPEe+0igxcrkILJ6CKxZapBEd56h9wpKi5apAXPly6zGF45Ig8aRrnVUJxMdFJvloBJ0iBTwyRsRr8BIbcZdR+huzuT5MaqAv0GWWcctC/kRbo8O50VwboRiKuJB51DyUpq5kkMFWAE9/T7In9Z8oW0Y5FOWb5eo/+wbRWF3gfK7rZb0QC8m0WLcsvo1Yqi32WihBpzGrk63Fmg2OM2ENJexBGS4b2ze0EryO/GFOEjsaP6G92K89rS14kzJkmL4='
stages:
  - name: Quality
  - name: Test
  - name: Build
  - name: Deploy
  - name: Smoke Test
  - name: Monitor
jobs:
  include:
    - stage: Quality
      env: step=Snyk vulnerability check
      name: Snyk vulnerability check
      script: snyk test
    - env: step=Detect secrets in files
      name: Detect secrets in files
      script:
        - npm run detect-secrets $(git ls-files)
    - env: step=Run commit lint
      name: Run commit lint
      script:
        - commitlint-travis
    - env: step=Run ESLint check
      name: Run ESLint check
      script:
        - npm run lint:verify
    - env: step=Run Prettier check
      name: Run Prettier check
      script:
        - npm run prettier:verify
    - stage: Test
      env: step=Run tests and Sonar Scanner
      name: Run tests and Sonar Scanner
      script:
        - touch .env
        - npm test
        - sonar-scanner
    - env: step=Run contract tests
      name: Run contract tests
      before_script:
        - npm start &
      script:
        - npm run build:postman
        - npm run test:api
    - stage: Build
      env: step=Build and Publish image
      name: Build and Publish image
      script:
        - ./scripts/buildAndPublish.sh
    - stage: Deploy
      env: step=Deploy the images
      name: Deploy the images
      script:
        - ./scripts/deploy.sh
    - stage: Smoke Test
      env: step=Run contract tests
      name: Run contract tests
      script:
        - npm run build:postman
        - npm run test:api -- --env-var "baseUrl=$APP_HOST"
    - stage: Monitor
      env: step=Run Snyk Monitor
      name: Run Snyk Monitor
      script: snyk monitor
env:
  global:
    # SYNK_TOKEN
    - secure: 'tqaAOrprSrFPx1rEWdPY4MkQ7+GjncNb/cZVtIjmGDl5YcNna/TtC/4TkEtXG4/1M6etMrxxEKQbS3SrQP9dBvAGyPnhy9NuTZktB143wePGbGzdRbIiKarvTZl38sWkpyn7oIgltFKImSszYxUQBhw6RUseFLWHNq4eejn1idbkRLNrmK0cdUOH5IwQB/yB5TaRRxFZiYOXMgf/HvVgnln2hozSTvcY30Dy59qrz4bZqQwvyqa3wk5TRjhQI/1KEDAfK2i/yHiYUZ6f96YJZ2qfHCInJExBWuO0ZQ0MGhkYdRiGNfJODJ5srIjHgpel72c+rSv6CdampQo8R8MpCyaCgRjQUQzml9x0oQI3sbk8UJRafaDkpgTMlg7Eka+qBdB6sZP2QbJvZoKrAraT6NpLp8vyxF1df5uvdrN91wvT6orzIQ0QGRVyT2YYcvYHwf0XGTloJVHSDK53bc1GpNYU3UHIt+6a6UqmxTeQRSU7CC3r06CC2XHvsRPEF7hI+0+2UQqTsd2vLF2ECjHJoDl3aTCi/sLaSvMqidwF8Z6hFO9Gn7rfgrCI4oZpNTBOJxrg7TmdUOq+U95Z+NsN4YV8DgqXElt6R7EIF8E0/6MWeKCZopEbnvG6jjDEbLhawBkU6nvw209Mhw9gwFNgJ9tD4frMSE1vbJX7iKq6LnU='
    # PACT_BROKER_TOKEN
    - secure: 'TDL/IHNUE6moIvAQWi51kkCLJQQbWl5g/Hzl5keLzsyi2zf2H87BVSaD11oHjhyF46KM/Xw/uEfGbOxWigmTE1f/2PpIuBOemNpfoVZxBQ2qXTu5QSMMZnxm/k2UYMPnlJX+/9JztNkyxl7q5mvVu1qKSVKCcsI+ked8phs99HavHKMxexFrVR7Ngbg1UtNAnb575amPs2vjj/vwjOsvBuh/jlJcxoOhFuFAnkL9ROv9ChZqxiwEl/H2mTG0jbpJMvAWyttPNgH74W40+yqZBhE+PCmBe6JbTAp+b/NF3ey1MpO8oJmPL8rYAT7BgCPAw30YcyS9qcVAdZ7iyfrQBoPINvR9PGWOXd6l3TOXDbvUTbVAdajze6nP+Wx0TOav1Ij+dIFq9EXiRAkpjbutHGwSPzui+EhCJXHgTB2Rdp/7laxz82LgKCKTImW0vEA7Yk5j0WQLpKWeKD++/1j/8IWrEJevDjRr8Qd+Lf+WWFiGP4azdoWy2z3WDWJ80zfH3+/kMjhmzRFCaQX5B5cDOZ+Zx3kNkwFjXVm9Uxvg9n9JrxK7CGY2JIGAys7RSfOO5QajH5YFpYLP1GNwtSU6pHoog2G2HRJHZcXynhJ9OJCnO59SUo3owJ6U1KpQ5r4I+ys3KWDrKChYuQ5y9KrCgqErwyUkJW/rGy0KFTgVUQ4='
