version: '3.4'

services:
  gotreasa-blue-tic-tac-toe: # TODO rename
    image: gotreasa-blue-tic-tac-toe # TODO rename
    container_name: gotreasa-blue-tic-tac-toe # TODO rename
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 9080:9080

  swagger:
    image: swagger-ui
    container_name: swagger-ui
    build:
      context: .
      dockerfile: ./Dockerfile-swagger
    ports:
      - 8080:8080
