const LEFT_COLUMN = [0, 3, 6];
const MIDDLE_COLUMN = [1, 4, 7];
const RGHT_COLUMN = [2, 5, 8];
const TOP_ROW = [0, 1, 2];
const MIDDLE_ROW = [3, 4, 5];
const BOTTOM_ROW = [6, 7, 8];
const BACKWARD_DIAGONAL = [0, 4, 8];
const FORWARD_DIAGONAL = [2, 4, 6];

const TOP_ROW_LEFT = 0;
const TOP_ROW_CENTRE = 1;
const TOP_ROW_RIGHT = 2;
const MIDDLE_ROW_LEFT = 3;
const MIDDLE_ROW_CENTRE = 4;
const MIDDLE_ROW_RIGHT = 5;
const BOTTOM_ROW_LEFT = 6;
const BOTTOM_ROW_CENTRE = 7;
const BOTTOM_ROW_RIGHT = 8;

module.exports = {
  LEFT_COLUMN,
  MIDDLE_COLUMN,
  RGHT_COLUMN,
  TOP_ROW,
  MIDDLE_ROW,
  BOTTOM_ROW,
  BACKWARD_DIAGONAL,
  FORWARD_DIAGONAL,
  TOP_ROW_LEFT,
  TOP_ROW_CENTRE,
  TOP_ROW_RIGHT,
  MIDDLE_ROW_LEFT,
  MIDDLE_ROW_CENTRE,
  MIDDLE_ROW_RIGHT,
  BOTTOM_ROW_LEFT,
  BOTTOM_ROW_CENTRE,
  BOTTOM_ROW_RIGHT,
};
